# Generated by Django 5.1.6 on 2025-03-15 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('curp', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=30)),
                ('fecha_nac', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_pl', models.CharField(max_length=20)),
                ('mensualidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inscripcion', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
                ('retrasado', models.BooleanField()),
                ('curp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor.plan'),
        ),
    ]
